#!/bin/bash

function gen_deps() {
  local include_dirs="$1"
  local src_prefix="$2"
  local depsfile="$3"
  local objsfile="$4"
  local command="$5"
  local filter="$6"
  for file in $(find $src_prefix -type f $filter); do
    local objfile=${file/%c/o}
    objfile='$(OBJ_DIR)/'${objfile//\//-}
    echo -n "$objfile" ':' >> "$depsfile"
    gcc -MM "$file" $include_dirs | sed -E -e 's/^.*://; s/[^\\]$/\0 | create_dir/' >> "$depsfile"
    echo -e "\t$command\n" >> "$depsfile"
    echo "$objfile" \\ >> "$objsfile"
  done
}

echo "" > deps.mk
echo "OBJECTS = \\" > objects.mk

gen_deps '' 'src/' deps.mk objects.mk '$(CC) $(CFLAGS) -c -o $@ $<' '-name *.c'
exit 0
